### ISSUE TITLE
I would like to join your team and contribute with my many years of experience and skills.

### ISSUE THREAD

**Issue by johnsmith0212** [DigitalProductPassport/SmartContracts#1]
Hi, I'm Ethan Tan, a seasoned web full-stack and blockchain developer with over 8 years of experience in the industry. I specialize in building robust, scalable web applications and innovative blockchain solutions. Leveraging my expertise in frameworks like React.js, Vue.js, and Next.js, along with my proficiency in Solidity for smart contract development, I deliver high-quality, secure, and efficient solutions tailored to meet your specific needs.

**Comment by lmtrarbach** [comment]
Hey John ! Defo looking foward for your help. I just need to read a bit on the security and project contribitors structure and will give you the permissions to collaborate. 
Just give me few days and will grant you that. 

Thanks a million for your interest.

**Comment by lmtrarbach** [comment]
Ops mistake here.

John I'm happy to add you to the project. I'm looking forward for any help. I will just ask you few days as I need to add some security and structure the roles and the basic pipelines before adding more contributor. Just give me few days.

**Comment by johnsmith0212** [comment]
okay
I will wait

**Comment by lmtrarbach** [comment]
Could not work on the pipelines yet but gave you write permissions on the repository.

**Comment by johnsmith0212** [comment]
What tasks do you need me to help you with?

**Comment by lmtrarbach** [comment]
Look I'm not an expert in solidity  so is very likely that i dont followed good pratices. Could you give a look at the smart contracts and see if there's any bad pratice there?  I have cleanup a bit and update the packages.json but would be good to have your eyes on it. 
Also if you want to improve the test scenarios to get any error of logic that I could have done while writing it would be amazing. 

I'm working on getting an small SDK to deploy the contracts and soon will publish yo have your feedback.  Thank you!

**Comment by johnsmith0212** [comment]
I want to help you

-Contact Info
skype: https://join.skype.com/invite/FVUI6gLcYgAE
telegram: https://t.me/ethantan1116
slack: https://join.slack.com/t/ksc-xme4972/shared_invite/zt-2ld45idp2-G9HkxP_wX4ctwQshyPM7Ig
discord: https://discord.gg/VxnfdY4bS4

**Comment by lmtrarbach** [comment]
Tried to find you on discord but it directs to channels and not a specific user.  When you have some time can reach me on ltrarbach, I appreciate your offer for contribuite.

**Comment by johnsmith0212** [comment]
okay
Do you have telegram?
